bookings/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import generate_receipt
from django.conf import settings
from django.conf.urls.static import static

app_name = 'bookings'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bookings/logout.html'), name='logout'),
    path('', views.GeneratorListView.as_view(), name='generator_list'),
    path('book/<int:generator_id>/', views.book_generator, name='book_generator'),
    path('my-bookings/', views.UserBookingListView.as_view(), name='user_bookings'),
    path('generate_receipt/<int:booking_id>/', views.generate_receipt, name='generate_receipt'),
    path('receipt/<int:booking_id>/', views.generate_receipt, name='receipt'),
    path('initiate-payment/', views.initiate_payment, name='initiate_payment'),
    path('process-payment/', views.UserBookingListView.as_view(), name='process_payment'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('about-us/', views.about_us, name='about_us'),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

generator_booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookings.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='bookings/password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='bookings/password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='bookings/password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='bookings/password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

bookings/models.py
from django.db import models
from django.contrib.auth.models import User

class Generator(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    power_output = models.DecimalField(max_digits=8, decimal_places=2)
    fuel_type = models.CharField(max_length=50, default='Petrol')
    availability = models.BooleanField(default=True)
    daily_price = models.DecimalField(max_digits=8, decimal_places=2, default='20.0')
    image = models.ImageField(upload_to='generator_images/', blank=True, null=True)

    # New field to store the date when the generator becomes available
    available_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name

class Booking(models.Model):
    generator = models.ForeignKey(Generator, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    
    def __str__(self):
        return f"{self.generator.name} - {self.user.username}"

class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(default='2023-01-01 00:00:00')

    def __str__(self):
        return self.name

bookings/forms.py
from django import forms
from .models import Booking,ContactMessage

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['start_date', 'end_date']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'message']

        from django import forms
from .models import Generator, Booking, ContactMessage

class GeneratorForm(forms.ModelForm):
    class Meta:
        model = Generator
        fields = ['name', 'description', 'power_output', 'fuel_type', 'availability', 'image']

bookings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Generator, Booking
from .forms import BookingForm
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_protect
from .forms import LoginForm
from datetime import datetime
from datetime import timedelta
from django.core.exceptions import ValidationError
from django.conf import settings   #--------
import stripe                      #--------
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.urls import reverse
from .forms import ContactForm
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)

from urllib.parse import urlparse, urlunparse

from django.conf import settings

# Avoid shadowing the login() and logout() views below.
from django.contrib.auth import REDIRECT_FIELD_NAME, get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ImproperlyConfigured, ValidationError
from django.http import HttpResponseRedirect, QueryDict
from django.shortcuts import resolve_url
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.http import url_has_allowed_host_and_scheme, urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from datetime import datetime, timedelta

UserModel = get_user_model()

stripe.api_key = settings.STRIPE_SECRET_KEY

class GeneratorListView(ListView):
    model = Generator
    template_name = 'bookings/generator_list.html'
    context_object_name = 'generators'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Calculate the available date based on today's date
        today = datetime.now().date()
        available_date = today + timedelta(days=1)  # Assuming the generator is available at least after one day

        context['available_date'] = available_date
        return context

def about_us(request):
    return render(request, 'bookings/about_us.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('bookings:login')
    else:
        form = UserCreationForm()
    return render(request, 'bookings/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('bookings:generator_list')
            else:
                messages.error(request, 'Invalid username or password.')
    else:
        form = LoginForm()

    return render(request, 'bookings/login.html', {'form': form})

def contact_us(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your message has been sent. We will get back to you soon.')
            return redirect('bookings:contact_us')  # Update the redirect to use the correct URL name
    else:
        form = ContactForm()
    return render(request, 'bookings/contact_us.html', {'form': form})

class PasswordContextMixin:
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {"title": self.title, "subtitle": None, **(self.extra_context or {})}
        )
        return context

class PasswordResetView(PasswordContextMixin, FormView):
    email_template_name = "registration/password_reset_email.html"
    extra_email_context = None
    form_class = PasswordResetForm
    from_email = None
    html_email_template_name = None
    subject_template_name = "registration/password_reset_subject.txt"
    success_url = reverse_lazy("password_reset_done")
    template_name = "registration/password_reset_form.html"
    title = _("Password reset")
    token_generator = default_token_generator

    @method_decorator(csrf_protect)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        opts = {
            "use_https": self.request.is_secure(),
            "token_generator": self.token_generator,
            "from_email": self.from_email,
            "email_template_name": self.email_template_name,
            "subject_template_name": self.subject_template_name,
            "request": self.request,
            "html_email_template_name": self.html_email_template_name,
            "extra_email_context": self.extra_email_context,
        }
        form.save(**opts)
        return super().form_valid(form)


INTERNAL_RESET_SESSION_TOKEN = "_password_reset_token"


class PasswordResetDoneView(PasswordContextMixin, TemplateView):
    template_name = "registration/password_reset_done.html"
    title = _("Password reset sent")


class PasswordResetConfirmView(PasswordContextMixin, FormView):
    form_class = SetPasswordForm
    post_reset_login = False
    post_reset_login_backend = None
    reset_url_token = "set-password"
    success_url = reverse_lazy("password_reset_complete")
    template_name = "registration/password_reset_confirm.html"
    title = _("Enter new password")
    token_generator = default_token_generator

    @method_decorator(sensitive_post_parameters())
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        if "uidb64" not in kwargs or "token" not in kwargs:
            raise ImproperlyConfigured(
                "The URL path must contain 'uidb64' and 'token' parameters."
            )

        self.validlink = False
        self.user = self.get_user(kwargs["uidb64"])

        if self.user is not None:
            token = kwargs["token"]
            if token == self.reset_url_token:
                session_token = self.request.session.get(INTERNAL_RESET_SESSION_TOKEN)
                if self.token_generator.check_token(self.user, session_token):
                    # If the token is valid, display the password reset form.
                    self.validlink = True
                    return super().dispatch(*args, **kwargs)
            else:
                if self.token_generator.check_token(self.user, token):
                    # Store the token in the session and redirect to the
                    # password reset form at a URL without the token. That
                    # avoids the possibility of leaking the token in the
                    # HTTP Referer header.
                    self.request.session[INTERNAL_RESET_SESSION_TOKEN] = token
                    redirect_url = self.request.path.replace(
                        token, self.reset_url_token
                    )
                    return HttpResponseRedirect(redirect_url)

        # Display the "Password reset unsuccessful" page.
        return self.render_to_response(self.get_context_data())

    def get_user(self, uidb64):
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64).decode()
            user = UserModel._default_manager.get(pk=uid)
        except (
            TypeError,
            ValueError,
            OverflowError,
            UserModel.DoesNotExist,
            ValidationError,
        ):
            user = None
        return user

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.user
        return kwargs

    def form_valid(self, form):
        user = form.save()
        del self.request.session[INTERNAL_RESET_SESSION_TOKEN]
        if self.post_reset_login:
            auth_login(self.request, user, self.post_reset_login_backend)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.validlink:
            context["validlink"] = True
        else:
            context.update(
                {
                    "form": None,
                    "title": _("Password reset unsuccessful"),
                    "validlink": False,
                }
            )
        return context


class PasswordResetCompleteView(PasswordContextMixin, TemplateView):
    template_name = "registration/password_reset_complete.html"
    title = _("Password reset complete")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["login_url"] = resolve_url(settings.LOGIN_URL)
        return context



@login_required(login_url='bookings:login')
def book_generator(request, generator_id):
    generator = get_object_or_404(Generator, pk=generator_id)
    
    if not generator.availability:

bookings/templates/base.html
<!-- base.html -->
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Generator Booking</title>

    <!-- Add the following links for the datepicker libraries -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Dark Mode CSS -->
    <link rel="stylesheet" href="{% static 'css/dark-mode.css' %}" id="dark-mode">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- Your other CSS and JavaScript files -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>

    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script>
        // Check if dark mode preference is stored in localStorage
        const storedMode = localStorage.getItem('darkMode');

        // Apply stored mode on page load
        if (storedMode === 'dark') {
            document.body.classList.add('dark-mode');
        }
    </script>

    <style>
        body {
            padding-top: 50px;
        }

        main {
            min-height: calc(100vh - 170px);
        }

        footer {
            background-color: #333;
            color: #fff;
            padding: 20px 0;
        }

        footer p {
            margin: 0;
        }

        footer .social-links a {
            color: #fff;
            margin-right: 10px;
            font-size: 18px;
        }

        footer .contact-info {
            margin-top: 10px;
            font-size: 14px;
        }

        #map {
            height: 200px;
            left: 0;
        }
    </style>
</head>
<body class="light-mode"style="background-image: url('{% static 'images/bg.jpg' %}');">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'bookings:about_us' %}">Generator Booking</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bookings:user_bookings' %}">My Bookings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bookings:logout' %}">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bookings:generator_list' %}">Generators</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bookings:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bookings:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bookings:contact_us' %}">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" onclick="window.location.href='http://127.0.0.1:8000/admin/login/?next=/admin/auth/user/';">Admin Login </a> 
                            {% comment %}   Replace a with button is its not working {% endcomment %}
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <button id="dark-mode-toggle" class="btn btn-sm">
                                <i class="fa fa-moon"></i>
                            </button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container mt-5" style="background-image: url('{% static 'images/background.png' %}');">
        {% block content %}
        
        {% endblock %}
    </main>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-md-left">
                    <p>&copy; 2023 Generator Booking</p>
                  
                </div>
                <div class="col-md-6 text-center text-md-right">
                    <div class="social-links"><br/>
                        <br/>
                        <br/>
                        
                    </div>
                    <div class="contact-info">
                        <span>Contact: +918088389598</span><br/>
                        <br>
                        <span>Shop Address: Vidyagiri,Dharwad</span>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    

    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <script>
        // Dark mode toggle
        const darkModeToggle = document.getElementById('dark-mode-toggle');
        const body = document.body;

        darkModeToggle.addEventListener('click', () => {
            body.classList.toggle('dark-mode');

            // Store dark mode preference in localStorage
            if (body.classList.contains('dark-mode')) {
                localStorage.setItem('darkMode', 'dark');
            } else {
                localStorage.setItem('darkMode', 'light');
            }
        });

        // Check if dark mode preference is stored in localStorage on page load
        window.addEventListener('load', () => {
            const storedMode = localStorage.getItem('darkMode');
            if (storedMode === 'dark') {
                body.classList.add('dark-mode');
            }
        });

        // Initialize and display the map
        function initMap() {
            const mapElement = document.getElementById('map');
            const mapOptions = {
                center: { lat: 40.712776, lng: -74.005974 }, // Coordinates for New York City
                zoom: 12
            };
            const map = new google.maps.Map(mapElement, mapOptions);
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBfSInKmA7Ibd2GQaicbUtOs2o0EJyKWQo&callback=initMap" async defer></script>
</body>
</html>